### ISSUE TITLE
1.1.8 fails to reach 100.0C 

### ISSUE THREAD

**Issue by Ximidar** [Robo3D/Marlin#16]
1.1.8 disconnects the printer at about 80 degrees (80 - 90 C) 

I found this was due to MAX_BED_POWER being set to 200. I changed it back to 255 and was able to reach 100C on the bed. I believe it disconnected because the temperature took too long to get to it's target temperature and the watchdog kicked in. I also noticed that a PID change did not come along with the bed power decrease. If we want to keep MAX_BED_POWER at 200 we should also change the PID values to accompany the power decrease

**Comment by AllenMcAfee** [comment]
This issue was largely due to failures in the Heater PCB from the supplier.  This has been fixed with Heated Bed PCB V2.  Bed MAX POWER was limited to prevent burnout damage due to arcing from the Pogo Pin PCBA in Heated Bed V1.  Now that we have dropped Pogo Pins we have increased MAX_BED_POWER to 255.

PID values below have tested well with the settings above:
```  
  #define  DEFAULT_bedKp 107.41
  #define  DEFAULT_bedKi 21.29
  #define  DEFAULT_bedKd 135.50
```
