### ISSUE TITLE
[FR] Enable CASE_LIGHT_PIN

### ISSUE THREAD

**Issue by WheresWaldo** [Robo3D/Marlin#22]
### Feature Request

Please consider a slight modification to enable case lighting under g-code control. only two lines are necessary to provide support and uncommenting the define would allow direct control of additional LED lights added by the end user with appropriate hardware without the need to download firmware, recompiling and flashing firmware.

The two edits required are first in _pins_ROBOMB.h_ &/or _pins.ROBOC2.h_
`#define CASE_LIGHT_PIN	44  // MUST BE HARDWARE PWM (2, 3, 4, 5, 6, 7, 8, 9, 10, 44, 45) `

In _Configuration_adv.h_ the following change is required, uncomment the line
`#define CASE_LIGHT_ENABLE`

The end result is that you have control over a single color LED strip (user provided hardware). Control includes turning the LED strip(s) on or off as well as brightness control. I have outlined all the required hardware in this Projects thread on the Robo forum, http://community.robo3d.com/index.php?threads/g-code-controlled-case-lighting.19871/

That thread shows the installation and how to modify OctoPrint's _config.yaml_ to add a custom control so you can use the web interface to control case lighting,

**Comment by AllenMcAfee** [comment]
@WheresWaldo I have enabled this in the latest firmware.  I pulled the definition out of Config_adv and placed it in the pins doc for ROBOMB.  We are dropping the C2 pins list and consolidating to the one ROBOMB pin file. 

I am enabling this on pin 5 to start since ROBOMBs going forward will have the LED pins PWM enabled.  The current Mainboard 2.1.5 and below have a resistor that can be removed to enable PWM to the lights and controller fan (R28 and R47 by the extruder connector).  To keep it simple we are going to list CASE_LIGHT as pin 5 in the production firmware.  You're free to handle it on any pin you want in your own flavor, of course.

**Comment by WheresWaldo** [comment]
Thanks Allen, I already saw this in the source and saw that you are combining the pins file. That is smart. I also saw the drop drown resisters on the main board and I will be removing at least the FAN2 to give control of the lighting. I will also write up this mod for the forum so others can modify the 2.1.5 boards if they want. The cooling fan on Pin 6 doesn't really need PWM control so I will leave it. I am going to close this issue.
